
USE LojaSapatos
GO
-- VERIFICA SE A PROCEDURE JA EXISTE E SE EXISTIR APAGA A MESMA DO BANCO
IF OBJECT_ID ( 'sp_AtualizarProduto', 'P' ) IS NOT NULL 
    DROP PROCEDURE sp_AtualizarProduto;
GO


SET ANSI_NULLS ON 
GO
SET QUOTED_IDENTIFIER ON 
GO

CREATE PROCEDURE sp_AtualizarProduto(@idprod INT,@sub int)
AS
BEGIN
	SET NOCOUNT ON; 

	-- SEMPRE QUE VARIOS REGISTROS EM UMA OU MAIS TABELAS
	-- FOREM ALTERADOS/INSERIDOS DEVE-SE USAR TRANSACAO
	-- INICIO DA TRANSACAO
	BEGIN TRANSACTION

	BEGIN TRY

		UPDATE Produtos		
		SET QuantidadeProduto = QuantidadeProduto-(@sub)
		WHERE IDProd = @idprod
		COMMIT TRANSACTION

	END TRY
	BEGIN CATCH
	-- SE OCORRER ERRO TODAS AS ALTERERACOES DEVEM SER REVERTIDAS
	  ROLLBACK TRANSACTION 
	END CATCH  


END
GO

